services:
  backend:
    build:
      context: ./backend
      network: host
    container_name: habits_backend
    ports:
      - "3000:3000"
    env_file:
      - backend/.db.env
      - backend/.redis.env
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: cache
    volumes:
      - backend_logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      network: host
    container_name: habits_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:17
    container_name: habits_postgres
    restart: always
    env_file:
      - backend/.db.env
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  cache:
    image: redis:8.4-alpine
    container_name: habits_redis
    restart: always
    ports:
      - "6339:6379"
    env_file:
      - backend/.redis.env
    command: ["sh", "-c", "redis-server --requirepass $$REDIS_PASSWORD --save 60 1 --appendonly yes"]
    volumes:
      - redis_data:/data

  reverse-proxy:
    image: nginx:stable-alpine
    container_name: habits_nginx
    restart: always
    ports:
      - "81:81"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  redis_data:
    driver: local
  backend_logs:
    driver: local
