events {}

http {
  server {
      listen 81;
      server_name habits.com;

      location /api/ {
          proxy_pass http://backend:30/;
      }

      location /ws/ {
          proxy_pass http://backend:30/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
      }

      location / {
          proxy_pass http://frontend:80/;
      }
  }
}
