apiVersion: v1
kind: ConfigMap
metadata:
  name: habit-pet-config
  namespace: habit-pet
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: habitsdb
  REDIS_HOST: redis
  REDIS_PORT: "6379"
